export default {
  ROUTE_CURRENT_USER: 'ROUTE_CURRENT_USER',

  FETCH_USER_PROFILE_REQUESTING: 'FETCH_USER_PROFILE_REQUESTING',
  FETCH_USER_PROFILE_SUCCESS: 'FETCH_USER_PROFILE_SUCCESS',
  FETCH_USER_PROFILE_ERROR: 'FETCH_USER_PROFILE_SUCCESS',

  CREATE_USER_PROFILE: 'CREATE_USER_PROFILE',
  CREATE_USER_PROFILE_REQUESTING: 'CREATE_USER_PROFILE_REQUESTING',
  CREATE_USER_PROFILE_SUCCESS: 'CREATE_USER_PROFILE_SUCCESS',
  CREATE_USER_PROFILE_ERROR: 'CREATE_USER_PROFILE_ERROR',

  LOGIN_USER_PROFILE: 'LOGIN_USER_PROFILE',
  LOGIN_USER_PROFILE_REQUESTING: 'LOGIN_USER_PROFILE_REQUESTING',
  LOGIN_USER_PROFILE_SUCCESS: 'LOGIN_USER_PROFILE_SUCCESS',
  LOGIN_USER_PROFILE_ERROR: 'LOGIN_USER_PROFILE_ERROR',

  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
  UPDATE_USER_PROFILE_REQUESTING: 'UPDATE_USER_PROFILE_REQUESTING',
  UPDATE_USER_PROFILE_SUCCESS: 'UPDATE_USER_PROFILE_SUCCESS',
  UPDATE_USER_PROFILE_ERROR: 'UPDATE_USER_PROFILE_ERROR',

  FETCH_EVENTS: 'FETCH_EVENTS',
  FETCH_EVENTS_REQUESTING: 'FETCH_EVENTS_REQUESTING',
  FETCH_EVENTS_SUCCESS: 'FETCH_EVENTS_SUCCESS',
  FETCH_EVENTS_ERROR: 'FETCH_EVENTS_ERROR',

  SET_SAVE_EVENT_DATA: 'SET_SAVE_EVENT_DATA',
  CLEAR_SAVE_EVENT_DATA: 'CLEAR_SAVE_EVENT_DATA',
}
