export default {
    ROUTE_CURRENT_USER: 'ROUTE_CURRENT_USER',

    FETCH_USER_PROFILE: 'FETCH_USER_PROFILE',
    FETCH_USER_PROFILE_SUCCESS: 'FETCH_USER_PROFILE_SUCCESS',
    FETCH_USER_PROFILE_ERROR: 'FETCH_USER_PROFILE_SUCCESS'
}