export default {
  WHITE: '#FFFFFF',
  BLACK: '#000000',
  HIGHLIGHT: '#4094DF',

  BUTTON: '#FFFFFF',
  BORDER: '#CCCCCC',

  TEXT: '#000000',
  TITLE: '#B8B8B8',
  HIGHLIGHTED_TEXT: '#4094DF',
  PLACEHOLDER_TEXT: '#CCCCCC',

  UNDERLINE: '#F1F1F1',

  BACKGROUND: '#FFFFFF',
  BAR: '#FAFAFA',
  INACTIVE_TB_TINT_COLOR: '#CCCCCC'
}